# Generated by Django 2.2.7 on 2021-03-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='flag_active',
            field=models.IntegerField(default=0),
        ),
    ]
