# Generated by Django 2.2.7 on 2021-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_flag_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ola',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
