# Generated by Django 2.2.7 on 2021-03-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_ola'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='ola',
            new_name='winner',
        ),
    ]
